CREATE TABLE "bookings" (
	"id" varchar(50) PRIMARY KEY NOT NULL,
	"driver_id" varchar(50) NOT NULL,
	"driver_name" text NOT NULL,
	"car_model" text NOT NULL,
	"plate_number" varchar(20) NOT NULL,
	"booking_date" varchar(20) NOT NULL,
	"passenger_name" text NOT NULL,
	"passenger_phone" varchar(20) NOT NULL,
	"notes" text,
	"seats_booked" integer NOT NULL,
	"pickup" text NOT NULL,
	"dropoff" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"status" varchar(20) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "drivers" (
	"uID" text PRIMARY KEY NOT NULL,
	"user_id" varchar(50) NOT NULL,
	"phone" varchar(20) NOT NULL,
	"date_of_birth" date NOT NULL,
	"city" varchar(100) NOT NULL,
	"address" text NOT NULL,
	"national_id_or_ssn" varchar(50) NOT NULL,
	"driver_license_number" varchar(50) NOT NULL,
	"license_expiry_date" date NOT NULL,
	"driving_experience_years" integer NOT NULL,
	"has_criminal_record" boolean NOT NULL,
	"criminal_record_explanation" text,
	"consent_background_check" boolean NOT NULL,
	"consent_terms" boolean NOT NULL,
	"signature_name" varchar(100) NOT NULL,
	"vehicle_category" varchar(50) NOT NULL,
	"make" varchar(100) NOT NULL,
	"model" varchar(100) NOT NULL,
	"year" integer NOT NULL,
	"color" varchar(50) NOT NULL,
	"license_plate" varchar(20) NOT NULL,
	"seats_count" integer NOT NULL,
	"fuel_type" varchar(50) NOT NULL,
	"license_front" text NOT NULL,
	"license_back" text NOT NULL,
	"vehicle_registration" text NOT NULL,
	"vehicle_insurance" text NOT NULL,
	"vehicle_inspection" text NOT NULL,
	"profile_photo" text NOT NULL,
	"avatar" text,
	"rating" numeric(4, 2) DEFAULT '0',
	"total_trips" integer DEFAULT 0,
	"current_pos" jsonb,
	"capacity" integer DEFAULT 4,
	"occupied_seats" integer DEFAULT 0,
	CONSTRAINT "drivers_uID_unique" UNIQUE("uID")
);
--> statement-breakpoint
ALTER TABLE "drivers" ADD CONSTRAINT "drivers_user_id_users_uID_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("uID") ON DELETE cascade ON UPDATE no action;