import type { Metadata } from 'next';
import './globals.css';
import { Geist_Mono, JetBrains_Mono, Roboto } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';

import Image from 'next/image';
import Header from '@/components/header';

const roboto = Roboto({
  subsets: ['latin'], // choose subsets you need
  weight: ['400', '500', '700'], // pick font weights
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        roboto.className,
        geistMono.variable,
        'font-mono',
        jetbrainsMono.variable,
      )}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <Toaster />
            <Header />
            {children}
            <footer className="flex flex-row p-10 items-center gap-4">
              <Image
                src="/vercel.ico"
                width={80}
                height={80}
                alt="leeto_pelo_logo"
              />
              <h1>Leeto Pele Transportation</h1>
            </footer>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
